# -*- coding: utf-8 -*-
"""First ML project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z9VNp77J4Z0o5ebMYgrDv_x_-K9voV66
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import re

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

df = pd.read_excel("First ML project.xlsx")
df.to_csv("dataset.csv", index=False)

def clean_text(text):
    text = str(text)
    text = text.lower()
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df['clean_review'] = df['Review Text'].apply(clean_text)

X = df['clean_review']
y = df['Annotation']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

vectorizer = TfidfVectorizer()

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

model = LogisticRegression(max_iter=200)
model.fit(X_train_vec, y_train)

y_pred = model.predict(X_test_vec)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))